# Generated by Django 4.0.6 on 2022-09-06 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_score'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='questions.test'),
        ),
    ]
